many new projects

diff --git a/aaa-build-scripts_0.1/aaa-common-functions b/aaa-build-scripts_0.1/aaa-common-functions
--- a/aaa-build-scripts_0.1/aaa-common-functions
+++ b/aaa-build-scripts_0.1/aaa-common-functions
@@ -1,25 +1,50 @@
 #!/bin/bash
 
-shopt -s extglob
+# Avoid any encoding problems
+export LANG=C
 
+# check if messages are to be printed using color
+unset txtrst txtbld bldblu bldgrn bldred bldylw
+if [[ -t 2 ]]; then
+	# prefer terminal safe colobldred and bold text when tput is supported
+	if tput setaf 0 &>/dev/null; then
+		txtrst="$(tput sgr0)"
+		txtbld="$(tput bold)"
+		bldblu="${txtbld}$(tput setaf 4)"
+		bldgrn="${txtbld}$(tput setaf 2)"
+		bldred="${txtbld}$(tput setaf 1)"
+		bldylw="${txtbld}$(tput setaf 3)"
+		bldpur="${txtbld}$(tput setaf 5)"
+		bldcyn="${txtbld}$(tput setaf 6)"
+		bldwht="${txtbld}$(tput setaf 7)"
+		txtblu="$(tput setaf 4)"
+		txtgrn="$(tput setaf 2)"
+		txtred="$(tput setaf 1)"
+		txtpur="$(tput setaf 5)"
+		txtylw="$(tput setaf 3)"
+		txtcyn="$(tput setaf 6)"
+		txtwht="$(tput setaf 7)"
+	else
+		txtrst="\e[1;0m"
+		txtbld="\e[1;1m"
+		bldblu="${txtbld}\e[1;34m"
+		bldgrn="${txtbld}\e[1;32m"
+		bldred="${txtbld}\e[1;31m"
+		bldylw="${txtbld}\e[1;33m"
+		bldpur="${txtbld}\e[1;35m" # purple
+		bldcyn="${txtbld}\e[1;36m" # cyan
+		bldwht="${txtbld}\e[1;37m" # white
+		txtred='\e[0;31m' # red
+		txtgrn='\e[0;32m' # green
+		txtylw='\e[0;33m' # yellow
+		txtblu='\e[0;34m' # blue
+		txtpur='\e[0;35m' # purple
+		txtcyn='\e[0;36m' # cyan
+		txtwht='\e[0;37m' # white
+	fi
+fi
+readonly txtrst txtbld bldblu bldgrn bldred bldylw txtred txtgrn txtylw txtblu txtpur txtcyn txtwht
 
-	txtred='\e[0;31m' # red
-	txtgrn='\e[0;32m' # green
-	txtylw='\e[0;33m' # yellow
-	txtblu='\e[0;34m' # blue
-	txtpur='\e[0;35m' # purple
-	txtcyn='\e[0;36m' # cyan
-	txtwht='\e[0;37m' # white
-	bldred='\e[1;31m' # red - Bold
-	bldgrn='\e[1;32m' # green
-	bldylw='\e[1;33m' # yellow
-	bldblu='\e[1;34m' # blue
-	bldpur='\e[1;35m' # purple
-	bldcyn='\e[1;36m' # cyan
-	bldwht='\e[1;37m' # white
-	txtund=$(tput sgr 0 1) # Underline
-	txtbld=$(tput bold) # Bold
-	txtrst='\e[0m' # Text reset
 	
 	# Feedback indicators
 	aaa_any_key="${bldblu} ANY KEY ${bldwht}"
@@ -31,57 +56,49 @@ shopt -s extglob
 # dialog functions *********************************************************************************************************************************************
 #***************************************************************************************************************************************************************
 
-function AnyKey()
-{
-		echo -e " ${bldgrn}aaa-->${bldwht} press ${aaa_any_key} to continue  ${txtrst}"
-		read -n1 -s
-}
+
 
 function Info()
 {
 
-	#argument 1 text to display
-		# xxx .. text to display...
-		
-		echo -e " ${bldgrn}info-->${bldwht}$1${txtrst}"
+	local mesg=$1; shift
+	printf "${bldgrn}info-->${bldwht}${mesg}${txtrst}\n" "${bldwht}$@${txtrst}" >&2
+}
+
+
+ function AnyKey()
+{
+		Info "press ${aaa_any_key} to continue"
+		read -n1 -s
+}
 		
 function Fuck()
 {
-
-	#argument 1 text to display
-		# xxx .. text to display...
-		
-		echo -e "${bldred}ERROR!!!!!!-->$1${txtrst}"
+		local mesg=$1; shift
+		printf "${bldred}ERROR!!!!!!-->${bldwht}${mesg}{txtrst}\n" "${bldwht}$@${txtrst}" >&2
 		exit 2
 }
 
-}
 
 function Block()
 {
 
-	#argument 1 text to display
-		# xxx .. text to display...
-		
-		echo -e "${bldblu}block-->${txtgrn}$1${txtrst}"
+		local mesg=$1; shift
+		printf "${bldblu}block-->${bldwht}${mesg}${txtrst}\n" "${bldwht}$@${txtrst}" >&2
 }
 
 function Warn()
 {
 
-	#argument 1 text to display
-		# xxx .. text to display...
-		
-		echo -e "  ${bldylw}WARNING-->${bldwht}$1${txtrst}"
+		local mesg=$1; shift
+		printf "${bldylw}WARNING-->${bldwht}${mesg}${txtrst}\n" "${bldwht}$@${txtrst}" >&2
 }
 
 function Debug()
 {
 
-	#argument 1 text to display
-		# xxx .. text to display...
-		
-		echo -e "${bldpur}debug-->${bldwht}$1${txtrst}"
+		local mesg=$1; shift
+		printf "${bldpur}debug-->${bldwht}${mesg}${txtrst}\n" "${bldwht}$@${txtrst}" >&2
 		AnyKey
 }
 
@@ -104,6 +121,15 @@ function MenuActive()
 		
 		echo -e "${bldwht}key======  ${bldblu}$1${txtgrn} $2 ${txtrst}"
 }
+
+function Test()
+{
+	
+        "$@" || Fuck "<$@>""failed"
+  
+}
+
+
 
 function CheckMyDeps()
 {
@@ -186,7 +212,7 @@ function MakeADir()
 		#xxxxxx ...variable name name
 	
 	if [[ ! -d "$1" ]]; then
-			mkdir -p "$1" || Fuck "failed to make $1 directory"
+			Test mkdir -p "$1"
 	fi
 	
 	
@@ -240,9 +266,9 @@ if [[ "$dir_exists" -eq 1 ]]; then
 	Warn "i need to clean it out"
 	Warn "if thats not good for you ${aaa_ctrl_c} to quit"
 	AnyKey
-	rm -rf "$aaa_work_dir"
-	rm -rf "$aaa_build_location"
-	rm -rf "$aaa_build_result"
+	Test rm -rf "$aaa_work_dir"
+	Test rm -rf "$aaa_build_location"
+	Test rm -rf "$aaa_build_result"
 fi
 		
 
@@ -308,6 +334,31 @@ for pack_names in $2; do
 done
 
 }
+
+
+function FreshInstall()
+{
+
+apt-get update
+#apt-get dist-upgrade
+/etc/init.d/gdm3 stop > /dev/null 2>&1
+apt-get --no-upgrade --no-install-recommends install xinit
+apt-get --no-upgrade purge gdm3
+apt-get --no-upgrade purge "gnome-settings-daemon*"
+apt-get --no-upgrade purge "gnome-session*"
+apt-get --no-upgrade --no-install-recommends  install "cinnamon*" "muffin*" "cjs*" "nemo*"
+
+Info "chose muffin here in the next dialog"
+update-alternatives --config x-window-manager
+
+Info "chose cinnamon-session in the next dialog"
+update-alternatives --config x-session-manager
+
+
+Info "now type startx"
+}
+
+
 
 
 
diff --git a/dev/aaa-script-ref b/dev/aaa-script-ref
--- a/dev/aaa-script-ref
+++ b/dev/aaa-script-ref
@@ -20,7 +20,7 @@ done
 # srtip extensions
 NAME=$(echo "$I" | sed s/\.[iI][sS][oO]$//) #strip .iso extension if present
 
-
+#####################################################################################################################################################################################################
 
 #
 # NAME:		Image Mounting Script
@@ -92,6 +92,7 @@ if [ ${CD_IMAGE_EXT} == "cue" ]; then
 fi
 
 
+#####################################################################################################################################################################################################
 
 step "Installing XFS filesystem tools:"
 try rpm -i xfsprogs-*.rpm
@@ -150,7 +151,8 @@ try() {
         "$@" &
     fi
     
-    
+
+#####################################################################################################################################################################################################    
     
     echo "Reading system-wide config...." >&2
 . /etc/cool.cfg
@@ -160,6 +162,7 @@ if [ -r ~/.coolrc ]; then
 fi
 
 
+#####################################################################################################################################################################################################
 
 
 
@@ -940,4 +943,243 @@ done
 
 FANCYTTY=
 [ -e /etc/lsb-base-logging.sh ] && . /etc/lsb-base-logging.sh || true
+
+
+#!/bin/bash
+
+# Avoid any encoding problems
+export LANG=C
+
+# check if messages are to be printed using color
+unset ALL_OFF BOLD BLUE GREEN RED YELLOW
+if [[ -t 2 ]]; then
+	# prefer terminal safe colored and bold text when tput is supported
+	if tput setaf 0 &>/dev/null; then
+		ALL_OFF="$(tput sgr0)"
+		BOLD="$(tput bold)"
+		BLUE="${BOLD}$(tput setaf 4)"
+		GREEN="${BOLD}$(tput setaf 2)"
+		RED="${BOLD}$(tput setaf 1)"
+		YELLOW="${BOLD}$(tput setaf 3)"
+	else
+		ALL_OFF="\e[1;0m"
+		BOLD="\e[1;1m"
+		BLUE="${BOLD}\e[1;34m"
+		GREEN="${BOLD}\e[1;32m"
+		RED="${BOLD}\e[1;31m"
+		YELLOW="${BOLD}\e[1;33m"
+	fi
+fi
+readonly ALL_OFF BOLD BLUE GREEN RED YELLOW
+
+plain() {
+	local mesg=$1; shift
+	printf "${BOLD}    ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+msg() {
+	local mesg=$1; shift
+	printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+msg2() {
+	local mesg=$1; shift
+	printf "${BLUE}  ->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+warning() {
+	local mesg=$1; shift
+	printf "${YELLOW}==> WARNING:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+error() {
+	local mesg=$1; shift
+	printf "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+stat_busy() {
+	local mesg=$1; shift
+	printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}...${ALL_OFF}" >&2
+}
+
+stat_done() {
+	printf "${BOLD}done${ALL_OFF}\n" >&2
+}
+
+setup_workdir() {
+	[[ -z $WORKDIR ]] && WORKDIR=$(mktemp -d --tmpdir "${0##*/}.XXXXXXXXXX")
+}
+
+cleanup() {
+	[[ -n $WORKDIR ]] && rm -rf "$WORKDIR"
+	[[ $1 ]] && exit $1
+}
+
+abort() {
+	msg 'Aborting...'
+	cleanup 0
+}
+
+trap_abort() {
+	trap - EXIT INT QUIT TERM HUP
+	abort
+}
+
+trap_exit() {
+	trap - EXIT INT QUIT TERM HUP
+	cleanup
+}
+
+die() {
+	(( $# )) && error "$@"
+	cleanup 1
+}
+
+trap 'trap_abort' INT QUIT TERM HUP
+trap 'trap_exit' EXIT
+
+##
+#  usage : in_array( $needle, $haystack )
+# return : 0 - found
+#          1 - not found
+##
+in_array() {
+	local needle=$1; shift
+	local item
+	for item in "$@"; do
+		[[ $item = $needle ]] && return 0 # Found
+	done
+	return 1 # Not Found
+}
+
+##
+#  usage : get_full_version( [$pkgname] )
+# return : full version spec, including epoch (if necessary), pkgver, pkgrel
+##
+get_full_version() {
+	# set defaults if they weren't specified in buildfile
+	pkgbase=${pkgbase:-${pkgname[0]}}
+	epoch=${epoch:-0}
+	if [[ -z $1 ]]; then
+		if [[ $epoch ]] && (( ! $epoch )); then
+			echo $pkgver-$pkgrel
+		else
+			echo $epoch:$pkgver-$pkgrel
+		fi
+	else
+		for i in pkgver pkgrel epoch; do
+			local indirect="${i}_override"
+			eval $(declare -f package_$1 | sed -n "s/\(^[[:space:]]*$i=\)/${i}_override=/p")
+			[[ -z ${!indirect} ]] && eval ${indirect}=\"${!i}\"
+		done
+		if (( ! $epoch_override )); then
+			echo $pkgver_override-$pkgrel_override
+		else
+			echo $epoch_override:$pkgver_override-$pkgrel_override
+		fi
+	fi
+}
+
+##
+#  usage : lock( $fd, $file, $message )
+##
+lock() {
+	eval "exec $1>"'"$2"'
+	if ! flock -n $1; then
+		stat_busy "$3"
+		flock $1
+		stat_done
+	fi
+}
+
+##
+#  usage : slock( $fd, $file, $message )
+##
+slock() {
+	eval "exec $1>"'"$2"'
+	if ! flock -sn $1; then
+		stat_busy "$3"
+		flock -s $1
+		stat_done
+	fi
+}
+
+
+base_packages=(base-devel)
+makechrootpkg_args=(-c -n)
+
+cmd="${0##*/}"
+if [[ "${cmd%%-*}" == 'multilib' ]]; then
+	repo="${cmd%-build}"
+	arch='x86_64'
+	base_packages+=(multilib-devel)
+else
+	tag="${cmd%-build}"
+	repo=${tag%-*}
+	arch=${tag##*-}
+fi
+chroots='/var/lib/archbuild'
+clean_first=false
+
+usage() {
+	echo "Usage: $cmd [options] -- [makechrootpkg args]"
+	echo '    -h         This help'
+	echo '    -c         Recreate the chroot before building'
+	echo '    -r <dir>   Create chroots in this directory'
+	echo ''
+	echo "Default makechrootpkg args: ${makechrootpkg_args[*]}"
+	echo ''
+	exit 1
+}
+
+while getopts 'hcr:' arg; do
+	case "${arg}" in
+		c) clean_first=true ;;
+		r) chroots="$OPTARG" ;;
+		*) usage ;;
+	esac
+done
+
+# Pass all arguments after -- right to makepkg
+makechrootpkg_args+=("${@:$OPTIND}")
+
+if (( EUID )); then
+	die 'This script must be run as root.'
+fi
+
+if ${clean_first} || [[ ! -d "${chroots}/${repo}-${arch}" ]]; then
+	msg "Creating chroot for [${repo}] (${arch})..."
+
+	for copy in "${chroots}/${repo}-${arch}"/*; do
+		[[ -d $copy ]] || continue
+		msg2 "Deleting chroot copy '$(basename "${copy}")'..."
+
+		lock 9 "$copydir.lock" "Locking chroot copy '$copy'"
+
+		if [[ "$(stat -f -c %T "${copy}")" == btrfs ]]; then
+			{ type -P btrfs && btrfs subvolume delete "${copy}"; } &>/dev/null
+		fi
+		rm -rf --one-file-system "${copy}"
+	done
+	exec 9>&-
+
+	rm -rf --one-file-system "${chroots}/${repo}-${arch}"
+	mkdir -p "${chroots}/${repo}-${arch}"
+	setarch "${arch}" mkarchroot \
+		-C "/usr/local/share/devtools/pacman-${repo}.conf" \
+		-M "/usr/local/share/devtools/makepkg-${arch}.conf" \
+		"${chroots}/${repo}-${arch}/root" \
+		"${base_packages[@]}" || abort
+else
+	lock 9 "${chroots}/${repo}-${arch}/root.lock" "Locking clean chroot"
+	arch-nspawn \
+		-C "/usr/local/share/devtools/pacman-${repo}.conf" \
+		-M "/usr/local/share/devtools/makepkg-${arch}.conf" \
+		"${chroots}/${repo}-${arch}/root" \
+                pacman -Syu --noconfirm || abort
+fi
+
+msg "Building in chroot for [${repo}] (${arch})..."
+exec makechrootpkg -r "${chroots}/${repo}-${arch}" "${makechrootpkg_args[@]}"
+
 
diff --git a/dev/aaa-test b/dev/aaa-test
--- a/dev/aaa-test
+++ b/dev/aaa-test
@@ -1,28 +1,137 @@
-#!/bin/bash
 
-function GetRelease()
+
+# Avoid any encoding problems
+export LANG=C
+
+# check if messages are to be printed using color
+unset txtrst txtbld bldblu bldgrn bldred bldylw
+if [[ -t 2 ]]; then
+	# prefer terminal safe colobldred and bold text when tput is supported
+	if tput setaf 0 &>/dev/null; then
+		txtrst="$(tput sgr0)"
+		txtbld="$(tput bold)"
+		bldblu="${txtbld}$(tput setaf 4)"
+		bldgrn="${txtbld}$(tput setaf 2)"
+		bldred="${txtbld}$(tput setaf 1)"
+		bldylw="${txtbld}$(tput setaf 3)"
+		bldcyn="${txtbld}$(tput setaf 5)"
+		bldwht="${txtbld}$(tput setaf 6)"
+		txtblu="$(tput setaf 4)"
+		txtgrn="$(tput setaf 2)"
+		txtred="$(tput setaf 1)"
+		txtylw="$(tput setaf 3)"
+		txtcyn="$(tput setaf 5)"
+		txtwht="$(tput setaf 6)"
+	else
+		txtrst="\e[1;0m"
+		txtbld="\e[1;1m"
+		bldblu="${txtbld}\e[1;34m"
+		bldgrn="${txtbld}\e[1;32m"
+		bldred="${txtbld}\e[1;31m"
+		bldylw="${txtbld}\e[1;33m"
+		bldpur="${txtbld}\e[1;35m" # purple
+		bldcyn="${txtbld}\e[1;36m" # cyan
+		bldwht="${txtbld}\e[1;37m" # white
+		txtred='\e[0;31m' # red
+		txtgrn='\e[0;32m' # green
+		txtylw='\e[0;33m' # yellow
+		txtblu='\e[0;34m' # blue
+		txtpur='\e[0;35m' # purple
+		txtcyn='\e[0;36m' # cyan
+		txtwht='\e[0;37m' # white
+	fi
+fi
+readonly txtrst txtbld bldblu bldgrn bldred bldylw txtred txtgrn txtylw txtblu txtpur txtcyn txtwht
+
+	
+	# Feedback indicators
+	aaa_any_key="${bldblu} ANY KEY ${bldwht}"
+	aaa_any_other_key="${bldblu} ANY OTHER KEY ${bldwht}"
+	aaa_ctrl_c="${bldcyn} CTRL-C ${bldwht}"
+
+
+
+# dialog functions *********************************************************************************************************************************************
+#***************************************************************************************************************************************************************
+
+function AnyKey()
+{
+		echo -e " ${bldgrn}aaa-->${bldwht} press ${aaa_any_key} to continue  ${txtrst}"
+		read -n1 -s
+}
+
+function Info()
 {
 
-	#first argument dl link
-		#xxxxxx ...variable name name
-release_version=$(curl -s https://github.com/linuxmint/$1/releases | grep -m 3 "/linuxmint/$1/archive/" | sed 's/.*.zip"//' | sed -n 's/.*\///p' | sed 's/".*//')
-Info " i made thew relese version as $release_version"
+	local mesg=$1; shift
+	printf "${bldgrn}info-->${bldwht}${mesg}${txtrst}\n" "${bldwht}$@${txtrst}" >&2
 		
-aaa_escape=0
-while [[ $aaa_escape -eq 0 ]]; do
-	wget "https://github.com/linuxmint/Cinnamon/archive/$release_version"
-	if [[ ! $? -eq 0 ]]; then
-		Warn "failed to download the release version of $1"
-		Warn "since with this build i cant miss this download i need to try again"
-		Warn "or it could be down to the webpage formate changing"
-		Warn "if thats not good for you ${aaa_ctrl_c} to quit"
-		AnyKey
-	else
-		tar -xzf $1*.tar.gz
-		aaa_escape=1
-	fi
-done
+		
+function Fuck()
+{
+
+	#argument 1 text to display
+		# xxx .. text to display...
+		
+		echo -e "${bldred}ERROR!!!!!!-->$$@{txtrst}"
+		exit 2
+}
 
 }
 
-GetRelease nemo
+function Block()
+{
+
+	#argument 1 text to display
+		# xxx .. text to display...
+		
+		echo -e "${bldblu}block-->${txtgrn}$@{txtrst}"
+}
+
+function Warn()
+{
+
+	#argument 1 text to display
+		# xxx .. text to display...
+		
+		echo -e "  ${bldylw}WARNING-->${bldwht}$@{txtrst}"
+}
+
+function Debug()
+{
+
+	#argument 1 text to display
+		# xxx .. text to display...
+		
+		echo -e "${bldpur}debug-->${bldwht}$@${txtrst}"
+		AnyKey
+}
+
+function MenuInactive()
+{
+	#argument 1 menu key
+		# x .. key to display
+	#argument 2 text to display
+		# xxx .. text to display...
+		
+		echo -e "${bldwht}key======  ${bldblu}$1${txtcyn} $2 ${txtrst}"
+}
+
+function MenuActive()
+{
+	#argument 1 menu key
+		# x .. key to display
+	#argument 2 text to display
+		# xxx .. text to display...
+		
+		echo -e "${bldwht}key======  ${bldblu}$1${txtgrn} $2 ${txtrst}"
+}
+
+function Test()
+{
+	
+        "$@" || Fuck "$@ failed"
+  
+}
+
+Info "info" "info2" "info3"
