cinnamon build now works in full,many new options

diff --git a/aaa-build-scripts_0.1/aaa-build-cinnamon b/aaa-build-scripts_0.1/aaa-build-cinnamon
--- a/aaa-build-scripts_0.1/aaa-build-cinnamon
+++ b/aaa-build-scripts_0.1/aaa-build-cinnamon
@@ -11,12 +11,17 @@ Usage() {
   cat <<EOF
 usage: ${0##*/} [options] distro
 
-  Currently this script takes two options
+   Currently this script takes two options
   and one argument
   -d < distro >
   -d <kali|stable|unstable|testing|ubuntu>
-  unlike the git version this script
-  builds the latest releases
+  -g [build from git sources]
+  
+  This script uses pbuilder and reprepro
+  to build cinnamon git or releases
+   for the desired distro
+  (including kali)
+  all packaging follows debian guidelines
 
 EOF
 }
@@ -63,6 +68,10 @@ while getopts ":d:" opt; do
 									  *) Fuck "<-d $OPTARG> is not valid, needs to be <-d kali,stable,unstable,testing or ubuntu>"  ;;
  
 		esac ;;
+	g) Info "-g recieved all builds will be from git, that ok with you ?"
+		AnyKey
+		aaa_cinnamon_git_list="$aaa_cinnamon_release_list $aaa_cinnamon_git_list"
+		aaa_cinnamon_release_list="" ;;
    \?) Fuck "Invalid option: -$OPTARG" ;;
     :) Fuck "Option -$OPTARG requires a distro name, kali,stable,unstable,testing or ubuntu" ;;
   esac
@@ -81,10 +90,11 @@ else
 	exit 1
 fi
 
+
 ########## end of common header #############################################################################################################################################
 #check script dependencies
 
-CheckMyDeps "reprepro pbuilder sed cat find grep dpkg-source"
+CheckMyDeps "reprepro pbuilder sed cat find grep dpkg-source lynx"
 [[ $aaa_setup_build_base_complete == yes ]] || Fuck "this script needs the base build environment setup, run aaa_setup-build-base"
 [[ $aaa_setup_build_env_complete == "yes" ]] || Fuck "this script needs the build environment setup, run aaa-setup-build-env"
 
@@ -108,26 +118,50 @@ function FailOkFilter()
 
 function GetRelease()
 {
-
-
-release_version=$(curl -s https://github.com/linuxmint/$1/releases | grep -m 3 "/linuxmint/$1/archive/" | sed 's/.*.zip"//' | sed -n 's/.*\///p' | sed 's/".*//')
 		
 aaa_escape=0
 while [[ $aaa_escape -eq 0 ]]; do
-	wget "https://github.com/linuxmint/$1/archive/$release_version"
+	wget $(lynx -dump -listonly https://github.com/linuxmint/$1/releases | sed '/master.zip/d' | grep -m 1 '.tar.gz' | sed -r 's/^.{6}//')
 	if [[ ! $? -eq 0 ]]; then
-		Warn "failed to download the release version of $1"
-		Warn "since with this build i cant miss this download i need to try again"
-		Warn "or it could be down to the webpage formate changing"
-		Warn "if thats not good for you ${aaa_ctrl_c} to quit"
-		AnyKey
+		case "$1" in
+		cinnamon-bluetooth|cinnamon-screensaver|cinnamon-themes|nemo-extensions) Warn "$1 failed to download, lynx often has a breakdown.
+this is not a critical component
+so can continue with the other components, or try to download
+again, i would advise you try again a few times"
+		Info "Any other key will download again"
+		MenuActive "q" "to pass onto the next package"
+		read -s -n1 aaa_tmpchr
+		[[ $aaa_tmpchr == q ]] && return 1 ;;
+						*) Warn "$1 failed to download and is a critical component of cinnamon, you must try again" 
+							AnyKey ;;
+	
+		esac
 	else
-		tar -xzf "$release_version"
-		rm -f "$release_version"
+		tar -xzf *.tar.gz
+		rm -f *.tar.gz
 		aaa_escape=1
 	fi
 done
 
+return 0
+
+}
+
+function CloneIt()
+{
+aaa_escape=0
+while [[ $aaa_escape -eq 0 ]]; do
+	Info "downloading git://github.com/linuxmint/$1.git"
+	git clone "git://github.com/linuxmint/$1.git"
+	if [[ ! $? -eq 0 ]]; then
+		Warn "git clone $1,, bugged out, mostly due to bad internet"
+		Warn "since with this build i cant miss a package i need to try again"
+		Warn "if thats not good for you ${aaa_ctrl_c} to quit"
+		AnyKey
+	else
+		aaa_escape=1
+	fi
+done
 }
 
 
@@ -155,11 +189,16 @@ with possible modifications"
 	if [[ $? -eq 0 ]]; then
 		#add package to result repo and working repo
 		cd "$aaa_build_result"
+#		for remove_targt in $(find . -maxdepth 1 -mindepth 1 -type f -name *.deb); do
+#			reprepro -Vb "$aaa_localrepo_dir" removematched $aaa_work_repo "*${${remove_targt#./}%.deb}*"  > /dev/null 2>&1
+#			reprepro -Vb "$aaa_localrepo_dir" removematched $aaa_debian_distro "*${${remove_targt#./}%.deb}*"  > /dev/null 2>&1
+#		done
 		Test reprepro -b "$aaa_localrepo_dir" includedeb $aaa_work_repo *.deb
 		Test reprepro -b "$aaa_localrepo_dir" include $aaa_debian_distro *.changes
 	
 		#clean up
-		find . -maxdepth 1 -mindepth 1 -type f -exec mv -f '{}' "$aaa_cinnamon_cache_dir/release-builds/$aaa_debian_distro/$bdate" \;
+		[[ $1 == g ]] && find . -maxdepth 1 -mindepth 1 -type f -exec mv -f '{}' "$aaa_cinnamon_cache_dir/git-builds/$aaa_debian_distro/$bdate" \;
+		[[ $1 == g ]] || find . -maxdepth 1 -mindepth 1 -type f -exec mv -f '{}' "$aaa_cinnamon_cache_dir/release-builds/$aaa_debian_distro/$bdate" \;
 	else
 		FailOkFilter "$name"
 	fi
@@ -175,10 +214,11 @@ with possible modifications"
 function BuildIt()
 {
 	#one argument, git repo name -- is extensions ?
+	#second argument is it a git build?
 if [[ $1 == "nemo-extensions" ]]; then
-	cd "$cinnamon_release_dir/nemo-extensions"-*
+	here=$(pwd)
+	cd "$here/nemo-extensions"
 	for _extension in $(ls -d */); do
-		cd "$cinnamon_release_dir/nemo-extensions"-*
 		Block "building $_extension "
 		if [[ ${_extension%%/} = "git" ]]; then
 			continue
@@ -187,12 +227,13 @@ if [[ $1 == "nemo-extensions" ]]; then
 		cd $aaa_work_dir/${_extension%%/}
 		PatchEm ${_extension%%/}
 		BuildOne ${_extension%%/}
+		cd "$here/nemo-extensions"
 	done
 else
-	cp -R -p "$1"-* $aaa_work_dir
-	cd $aaa_work_dir/$1-*
+	cp -R -p "$1"* $aaa_work_dir
+	cd $aaa_work_dir/$1*
 	PatchEm "$1"
-	BuildOne "$1"
+	BuildOne "$1" "$2"
 fi
 
 }
@@ -202,6 +243,7 @@ fi
 
 CleanMyBuildArea
 MakeADir "$aaa_cinnamon_cache_dir/release-builds/$aaa_debian_distro/$bdate"
+MakeADir "$aaa_cinnamon_cache_dir/git-builds/$aaa_debian_distro/$bdate"
 
 #update / create base immage
 UpdateBase
@@ -214,8 +256,8 @@ CleanMyRepo  $aaa_work_repo "cinnamon muffin nemo cjs"
 
 
 #check for previous working copy
-if [[ -d "$cinnamon_release_dir" ]]; then
-	Info "$cinnamon_release_dir already exists"
+if [[ -d "$aaa_cinnamon_sources_release" ]]; then
+	 Info "$aaa_cinnamon_sources_release already exists"
 	MenuActive "k" "to keep all sources"
 	MenuActive "s" "to to decide weather to keep individual sources"
 	MenuActive "q" "to quit with a return of 1"
@@ -225,53 +267,95 @@ if [[ -d "$cinnamon_release_dir" ]]; then
 		q) exit 1 ;;
 		k) decide="keep" ;;
 		s) decide="choose" ;;
-		*) rm -fr $cinnamon_release_dir 
-			MakeADir "$cinnamon_release_dir" ;;
+		*) rm -fr "$aaa_cinnamon_sources_release"
+			MakeADir "$aaa_cinnamon_sources_release" ;;
 	esac
 else
-	MakeADir "$cinnamon_release_dir" 
+	MakeADir "$aaa_cinnamon_sources_release" 
 fi
 
-
-
-#fetch all latest releaes and build in order, with choices over sources
-
-
-for _package in $aaa_cinnamon_git_list; do
-	if [ -d "$cinnamon_release_dir/$_package"-* ]; then
-		Info "$cinnamon_release_dir/$_package already exists"
+for _package in $aaa_cinnamon_release_list; do
+	if [ -d "$aaa_cinnamon_sources_release/$_package"* ]; then
+		Info "$aaa_cinnamon_sources_release/$_package already exists"
 		case $decide in
-			keep) Info "keep all sources is on! keeping source $cinnamon_release_dir/$_package"
-				cd "$cinnamon_release_dir"
+			keep) Info "keep all sources is on! keeping source $aaa_cinnamon_sources_release/$_package and building from it"
+					cd "$aaa_cinnamon_sources_release"
+					BuildIt "$_package" ;;
+		choose) Info "choose is on! you get a choice with each package its Christmas!"
+					MenuActive "k" "to keep these sources and build from them"
+					MenuActive "d" "to delete old directory and fetch fresh from git"
+					MenuActive "any other key" "to skip fetching and or building"
+					read -s -n1 aaa_tmpchr
+					case $aaa_tmpchr in
+						k) Info "keeping source $aaa_cinnamon_sources_release/$_package building from it"
+							cd "$aaa_cinnamon_sources_release"
+							BuildIt "$_package" ;;
+						d) rm -fr "$aaa_cinnamon_sources_release/$_package"*
+							cd "$aaa_cinnamon_sources_release"
+							GetRelease "$_package" && BuildIt "$_package" ;;
+						*) Info "skipping building $aaa_cinnamon_sources_release/$_package" ;;
+					esac ;;
+			*) Fuck "Internal error" ;;
+		esac
+	else
+		cd "$aaa_cinnamon_sources_release"
+		GetRelease "$_package" && BuildIt "$_package" 
+	fi
+done
+
+#check for previous working copy
+if [[ -d "$aaa_cinnamon_sources_git" ]]; then
+	 Info "$aaa_cinnamon_sources_git already exists"
+	MenuActive "k" "to keep all git sources"
+	MenuActive "s" "to to decide weather to keep individual sources"
+	MenuActive "q" "to quit with a return of 1"
+	MenuActive "any other key" "delete old directory"
+	read -s -n1 aaa_tmpchr
+	case "$aaa_tmpchr" in
+		q) exit 1 ;;
+		k) decide="keep" ;;
+		s) decide="choose" ;;
+		*) rm -fr "$aaa_cinnamon_sources_git"
+			MakeADir "$aaa_cinnamon_sources_git" ;;
+	esac
+else
+	MakeADir "$aaa_cinnamon_sources_git" 
+fi
+
+cd "$aaa_cinnamon_sources_git"
+for _package in $aaa_cinnamon_git_list; do
+	if [ -d "$aaa_cinnamon_sources_git/$_package" ]; then
+		Info "$aaa_cinnamon_sources_git/$_package already exists"
+		case $decide in
+			keep) Info "keep all sources is on! keeping source $aaa_cinnamon_sources_git/$_package and building from it"
+				cd "$aaa_cinnamon_sources_git"
 				BuildIt "$_package" ;;
-		  choose) Info "chose to keep sources is on!"
+		  choose) Info "choose is on! you get a choice with each package its Christmas!"
 					MenuActive "k" "to keep these sources and build from them"
 					MenuActive "d" "to delete old directory and fetch fresh from git"
 					MenuActive "any other key" "to skip fetching and building"
 					read -s -n1 aaa_tmpchr
 					case $aaa_tmpchr in
-						k) Info "keeping source $cinnamon_release_dir/$_package"
-							cd "$cinnamon_release_dir"
-							BuildIt "$_package" ;;
-						d) rm -fr "$cinnamon_release_dir/$_package"-*
-							cd "$cinnamon_release_dir"
-							GetRelease "$_package"
-							BuildIt "$_package" ;;
-						*) Info "skipping building $cinnamon_release_dir/$_package" ;;
+						k) Info "keeping source $aaa_cinnamon_sources_git/$_package and building from it"
+							cd "$aaa_cinnamon_sources_git"
+							BuildIt "$_package" g ;;
+						d) rm -fr "$aaa_cinnamon_sources_git/$_package"
+							cd "$aaa_cinnamon_sources_git"
+							CloneIt "$_package" && BuildIt "$_package" g ;;
+						*) Info "skipping building $aaa_cinnamon_sources_git/$_package" ;;
 					esac ;;
 			  *) Fuck "Internal error" ;;
 		esac
 	else
-		cd "$cinnamon_release_dir"
-		GetRelease "$_package"
-		BuildIt "$_package" 
+		cd "$aaa_cinnamon_sources_git"
+		CloneIt "$_package" && BuildIt g "$_package" 
 	fi
 done
 
 
 
-cd $HOME
-apt-get update
-apt-get --no-upgrade --no-install-recommends install --reinstall "cinnamon*" "muffin*" "cjs*" "nemo*"
+#cd $HOME
+#apt-get update
+#apt-get --no-upgrade --no-install-recommends install --reinstall "cinnamon*" "muffin*" "cjs*" "nemo*"
 
 
diff --git a/aaa-env_0.1/aaa-common-functions b/aaa-env_0.1/aaa-common-functions
--- a/aaa-env_0.1/aaa-common-functions
+++ b/aaa-env_0.1/aaa-common-functions
@@ -61,8 +61,7 @@ readonly txtrst txtbld bldblu bldgrn bldred bldylw txtred txtgrn txtylw txtblu t
 function Info()
 {
 
-	local mesg=$1; shift
-	printf "${bldgrn}info-->${bldwht}${mesg}${txtrst}\n" "${bldwht}$@${txtrst}" >&2
+	echo -e "${bldgrn}info-->${bldwht}$@${txtrst}"
 }
 
 
@@ -74,8 +73,7 @@ function Info()
 		
 function Fuck()
 {
-		local mesg=$1; shift
-		printf "${bldred}ERROR!!!!!!-->${bldwht}${mesg}${txtrst}\n" >&2
+		echo -e "${bldred}ERROR!!!!!!-->${bldwht}$@${txtrst}"
 		exit 2
 }
 
@@ -83,22 +81,19 @@ function Fuck()
 function Block()
 {
 
-		local mesg=$1; shift
-		printf "${bldblu}block-->${bldwht}${mesg}${txtrst}\n" >&2
+		echo -e "${bldblu}block-->${bldwht}$@${txtrst}"
 }
 
 function Warn()
 {
 
-		local mesg=$1; shift
-		printf "${bldylw}WARNING-->${bldwht}${mesg}${txtrst}\n" >&2
+		echo -e "${bldylw}WARNING-->${bldwht}$@${txtrst}"
 }
 
 function Debug()
 {
 
-		local mesg=$1; shift
-		printf "${bldpur}debug-->${bldwht}${mesg}${txtrst}\n" >&2
+		echo -e "${bldpur}debug-->${bldwht}$@${txtrst}"
 		AnyKey
 }
 
@@ -125,7 +120,7 @@ function MenuActive()
 function Test()
 {
 	
-        "$@" || Fuck "<$@> failed"
+        "$@" || Fuck "$@ failed"
   
 }
 
@@ -142,7 +137,7 @@ for _checks in $1; do
 	if [[ ! $? -eq 0 ]]; then
 		Warn"----$1------ is a dependency for this script, want me to install it?"
 		MenuActive "q" "to quit and install $1 yourself"
-		MenuActive "any other key" "to apt-get install $1"
+		MenuActive "i" "to apt-get install $1"
 		read -s -n1 aaa_tmpchr
 		if [[ ! $aaa_tmpchr == q ]]; then
 			apt-get install "$1*"
@@ -284,37 +279,31 @@ function UpdateBase()
 {
 
 Block "creating/updating base pbuilder image"
-
-if [[ $aaa_build_env_setup_complete_yes_no == "yes" ]]; then
-
-	aaa_escape=0
-	if [[ -e "$aaa_base_gz_dir/$aaa_base_gz" ]]; then
-		while [[ $aaa_escape -eq 0 ]]; do
-			pbuilder --update
-			if [[ ! $? -eq 0 ]]; then
-				Warn "pbuilder --update bugged out, mostly due to failed downloads"
-				Warn "hence going to try again, if thats not good for you ${aaa_ctrl_c} to quit"
-				AnyKey
-			else
-				aaa_escape=1
-			fi
-		done
-	else
-		while [[ $aaa_escape -eq 0 ]]; do
-			pbuilder --create
-			if [[ ! $? -eq 0 ]]; then
-				Warn "pbuilder --update bugged out, mostly due to failed downloads"
-				Warn "hence going to try again, if thats not good for you ${aaa_ctrl_c} to quit"
-				AnyKey
-			else
-				aaa_escape=1
-			fi
-		done
-	fi
-
+aaa_escape=0
+if [[ -e "$aaa_base_gz_dir/$aaa_base_gz" ]]; then
+	while [[ $aaa_escape -eq 0 ]]; do
+		pbuilder --update
+		if [[ ! $? -eq 0 ]]; then
+			Warn "pbuilder --update bugged out, mostly due to failed downloads"
+			Warn "hence going to try again, if thats not good for you ${aaa_ctrl_c} to quit"
+			AnyKey
+		else
+			aaa_escape=1
+		fi
+	done
 else
-	Fuck "updating or creating requires $HOME/.pbuilderrc and aaa-setup-build-env to have been run"
+	while [[ $aaa_escape -eq 0 ]]; do
+		pbuilder --create
+		if [[ ! $? -eq 0 ]]; then
+			Warn "pbuilder --update bugged out, mostly due to failed downloads"
+			Warn "hence going to try again, if thats not good for you ${aaa_ctrl_c} to quit"
+			AnyKey
+		else
+			aaa_escape=1
+		fi
+	done
 fi
+
 
 }
 
