lots and lots, will document all the changes later

diff --git a/aaa-env_0.1/aaa-common-functions b/aaa-env_0.1/aaa-common-functions
--- a/aaa-env_0.1/aaa-common-functions
+++ b/aaa-env_0.1/aaa-common-functions
@@ -75,7 +75,7 @@ function Info()
 function Fuck()
 {
 		local mesg=$1; shift
-		printf "${bldred}ERROR!!!!!!-->${bldwht}${mesg}{txtrst}\n" "${bldwht}$@${txtrst}" >&2
+		printf "${bldred}ERROR!!!!!!-->${bldwht}${mesg}${txtrst}\n" >&2
 		exit 2
 }
 
@@ -84,21 +84,21 @@ function Block()
 {
 
 		local mesg=$1; shift
-		printf "${bldblu}block-->${bldwht}${mesg}${txtrst}\n" "${bldwht}$@${txtrst}" >&2
+		printf "${bldblu}block-->${bldwht}${mesg}${txtrst}\n" >&2
 }
 
 function Warn()
 {
 
 		local mesg=$1; shift
-		printf "${bldylw}WARNING-->${bldwht}${mesg}${txtrst}\n" "${bldwht}$@${txtrst}" >&2
+		printf "${bldylw}WARNING-->${bldwht}${mesg}${txtrst}\n" >&2
 }
 
 function Debug()
 {
 
 		local mesg=$1; shift
-		printf "${bldpur}debug-->${bldwht}${mesg}${txtrst}\n" "${bldwht}$@${txtrst}" >&2
+		printf "${bldpur}debug-->${bldwht}${mesg}${txtrst}\n" >&2
 		AnyKey
 }
 
@@ -125,7 +125,7 @@ function MenuActive()
 function Test()
 {
 	
-        "$@" || Fuck "<$@>""failed"
+        "$@" || Fuck "<$@> failed"
   
 }
 
@@ -141,11 +141,11 @@ for _checks in $1; do
 	command -v $_checks >/dev/null 2>&1
 	if [[ ! $? -eq 0 ]]; then
 		Warn"----$1------ is a dependency for this script, want me to install it?"
+		MenuActive "q" "to quit and install $1 yourself"
 		MenuActive "any other key" "to apt-get install $1"
 		read -s -n1 aaa_tmpchr
 		if [[ ! $aaa_tmpchr == q ]]; then
-			apt-get update
-			apt-get install "$1"
+			apt-get install "$1*"
 		else
 			Fuck "----$1------ is a dependency for this script,... quitting untill its met"
 		fi
@@ -212,7 +212,7 @@ function MakeADir()
 		#xxxxxx ...variable name name
 	
 	if [[ ! -d "$1" ]]; then
-			Test mkdir -p "$1"
+		Test mkdir -p "$1"
 	fi
 	
 	
@@ -266,9 +266,9 @@ if [[ "$dir_exists" -eq 1 ]]; then
 	Warn "i need to clean it out"
 	Warn "if thats not good for you ${aaa_ctrl_c} to quit"
 	AnyKey
-	Test rm -rf "$aaa_work_dir"
-	Test rm -rf "$aaa_build_location"
-	Test rm -rf "$aaa_build_result"
+	rm -rf "$aaa_work_dir"
+	rm -rf "$aaa_build_location"
+	rm -rf "$aaa_build_result"
 fi
 		
 
@@ -334,6 +334,47 @@ for pack_names in $2; do
 done
 
 }
+
+
+function PatchEm()
+{
+
+	case "$1" in
+		nemo) patch -p1 < "$aaa_patch_dir/remove_elevated_privelages_banner.patch" 
+			#allow pup-vm to replace gvfs
+			sed -i 's/gvfs (>= 1.3.2)/gvfs (>= 1.3.2) | pup-volume-monitor/' ./debian/control ;;
+			
+			nemo-preview) mkdir -p aaa-tmp
+							cd aaa-tmp
+							#DownLoad "http://dk.archive.ubuntu.com/ubuntu/pool/main/i/intltool/intltool_0.50.2-2_all.deb"
+							#reprepro -b "$aaa_localrepo_dir" includedeb  $aaa_work_repo *.deb || Fuck "something wrong with-- reprepro ---check the output"
+							rm -f * >/dev/null 2>&1 
+							cd ..
+							rm -fr aaa-tmp ;;
+			libgnome2-0*) sed -i 's/gvfs/gvfs | pup-volume-monitor/' ./DEBIAN/control ;;
+			gnome-applets*) sed -i 's/gvfs/gvfs | pup-volume-monitor/' ./DEBIAN/control ;;
+	
+	esac
+ 
+
+}
+
+
+function ProcessBeb() {
+rm -fr "$1/tmp"
+MakeADir "$1/tmp"
+dpkg-deb -x *.deb "$1/tmp"
+dpkg-deb --control *.deb "$1/tmp/DEBIAN"
+cd "$1/tmp"
+PatchEm "$2"
+cd ..
+rm -f *.deb
+dpkg -b "$1/tmp" "$2"
+
+
+}
+
+
 
 
 function FreshInstall()
